### ISSUE TITLE
email endpoint incorrect

### ISSUE THREAD

**Issue by ryanahall** [resend/archived-resend-go#7]
When sending an email using this lib, I receive a 404. It appears that the path is incorrect:

https://github.com/resendlabs/resend-go/blob/main/emails.go#LL36C50-L36C50

Should this be `email` instead of `emails`?

**Comment by simplesagar** [comment]
Opened https://github.com/resendlabs/resend-go/pull/10 to address this issue

**Comment by zenorocha** [comment]
This should be fixed now
